services:
  course:
    build:
      context: ..
      dockerfile: microservices/course-service/Dockerfile
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS="-javaagent:/application/BOOT-INF/lib/opentelemetry-javaagent-2.13.3.jar"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRIC_EXPORT_INTERVAL=15000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - shared-network

  review:
    build:
      context: ..
      dockerfile: microservices/review-service/Dockerfile
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS="-javaagent:/application/BOOT-INF/lib/opentelemetry-javaagent-2.13.3.jar"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRIC_EXPORT_INTERVAL=15000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - shared-network

  course-composite:
    build:
      context: ..
      dockerfile: microservices/course-composite-service/Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS="-javaagent:/application/BOOT-INF/lib/opentelemetry-javaagent-2.13.3.jar"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRIC_EXPORT_INTERVAL=15000
      - OTEL_INSTRUMENTATION_SPRING_WEB_EXCLUDE_PATTERNS=/actuator/prometheus
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - shared-network

  gateway-service:
    build:
      context: ..
      dockerfile: spring-cloud/gateway-service/Dockerfile
    mem_limit: 512m
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS="-javaagent:/application/BOOT-INF/lib/opentelemetry-javaagent-2.13.3.jar"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRIC_EXPORT_INTERVAL=15000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge